apiVersion: apps/v1
kind: Deployment

metadata:
  name: attendance-service
  namespace: dev

  labels:
    app: attendance-service

  annotations:
    kubernetes.io/change-cause: "Initial Attendance Service Deployment"

spec:
  replicas: 1

  selector:
    matchLabels:
      app: attendance-service

  template:
    metadata:
      labels:
        app: attendance-service

    spec:
      containers:
        - name: attendance-service

          image: 027742774373.dkr.ecr.us-east-1.amazonaws.com/attendance-service:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 3503

          env:
            - name: host
              valueFrom:
                configMapKeyRef:
                  name: attendance-service-config
                  key: DB_HOST

            - name: user
              valueFrom:
                secretKeyRef:
                  name: attendance-service-secret
                  key: DB_USER

            - name: password
              valueFrom:
                secretKeyRef:
                  name: attendance-service-secret
                  key: DB_PASSWORD

            - name: database
              valueFrom:
                configMapKeyRef:
                  name: attendance-service-config
                  key: DB_NAME

            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: attendance-service-config
                  key: PORT

            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: attendance-service-config
                  key: NODE_ENV

          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

          readinessProbe:
            httpGet:
              path: /
              port: 3503
            initialDelaySeconds: 20
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /
              port: 3503
            initialDelaySeconds: 60
            periodSeconds: 20