apiVersion: v1
kind: Service

metadata:
  name: attendance-service
  namespace: dev

spec:
  selector:
    app: attendance-service

  ports:
    - port: 3503
      targetPort: 3503
      protocol: TCP

  type: ClusterIP