apiVersion: apps/v1
kind: Deployment

metadata:
  name: student-service
  namespace: dev

  labels:
    app: student-service

  annotations:
    kubernetes.io/change-cause: "Initial Student Service Deployment"

spec:
  replicas: 1

  selector:
    matchLabels:
      app: student-service

  template:
    metadata:
      labels:
        app: student-service

    spec:
      containers:
        - name: student-service

          image: 027742774373.dkr.ecr.us-east-1.amazonaws.com/student-service:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 3501
          env:
            - name: host
              valueFrom:
                configMapKeyRef:
                  name: student-service-config
                  key: DB_HOST
            - name: user
              valueFrom:
                secretKeyRef:
                  name: student-service-secret
                  key: DB_USER

            - name: password
              valueFrom:
                secretKeyRef:
                  name: student-service-secret
                  key: DB_PASSWORD

            - name: database
              valueFrom:
                configMapKeyRef:
                  name: student-service-config
                  key: DB_NAME

            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: student-service-config
                  key: PORT

            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: student-service-config
                  key: NODE_ENV

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"

            limits:
              cpu: "250m"
              memory: "256Mi"

          readinessProbe:
            httpGet:
              path: /health
              port: 3501
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /health
              port: 3501
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3