apiVersion: v1
kind: Service

metadata:
  name: student-service
  namespace: dev
  labels:
    app: student-service

spec:
  type: ClusterIP

  selector:
    app: student-service

  ports:
    - name: http
      protocol: TCP
      port: 3501
      targetPort: 3501